task: convert_rosbag2_with_gt_to_annotated_t4_tlr
conversion:
  overwrite_mode: true
  # path to rosbag dir output by simulator
  input_base: ./data/rosbag2
  output_base: ./data/t4_annotated
  gt_label_base: ./data/tlr_label
  topic_list: ./config/rosbag2_to_t4/topic_list_tlr.yaml
  skip_timestamp: 2
  num_load_frames: 0
  workers_number: 16
  camera_sensors:
    - topic: /sensing/camera/camera6/image_raw/compressed
      channel: CAM_TRAFFIC_LIGHT_FAR
    - topic: /sensing/camera/camera7/image_raw/compressed
      channel: CAM_TRAFFIC_LIGHT_NEAR
  generate_frame_every: 1
  generate_frame_every_meter: 0
