task: convert_rosbag2_to_t4
description:
  scene: synthetic
conversion:
  # path to rosbag dir output by simulator
  input_base: ./data/rosbag2_synthetic
  output_base: ./data/synthetic_to_t4_format
  workers_number: 1
  skip_timestamp: 2.0
  num_load_frames: 200
  crop_frames_unit: 50  # crop frames from the end so that the number of frames is divisible by crop_frames_unit. Set to 0 or 1 so as not to crop any frames.
  object_topic_name: /ground_truth/objects
  object_msg_type: DetectedObjects
  world_frame_id: world
  lidar_sensor:
    topic: /lidar/concatenated/pointcloud
    channel: LIDAR_CONCAT
  camera_sensors: [] # synthetic data has no images
