task: convert_fastlabel_to_t4
description:
  visibility:
    full: "No occlusion of the object."
    most: "Object is occluded, but by less than 50%."
    partial: "The object is occluded by more than 50% (but not completely)."
    none: "The object is 90-100% occluded and no points/pixels are visible in the label."
  camera_index:
    CAM_FRONT_NARROW: 0
    CAM_FRONT_WIDE: 1
    CAM_FRONT_RIGHT: 2
    CAM_BACK_RIGHT: 3
    CAM_BACK_NARROW: 4
    CAM_BACK_WIDE: 5
    CAM_BACK_LEFT: 6
    CAM_FRONT_LEFT: 7

conversion:
  make_t4_dataset_dir: false # If true, the output directory includes t4_dataset directory (such as "scene_dir"/t4_dataset/data|annotation). If false, "scene_dir"/data|annotation.
  input_base: /mnt/fs_nas_4/comlops_dataset/20240822
  input_anno_base: /mnt/NVME_RAID0_36TB/tmp/tier4_perception_dataset/label_data_2409-2502/pcd_annotation
  output_base: /mnt/HDD_RAID0_120TB/comlops_dataset_conversion/fastlabel_with_3d-annotation/20241224_#7_240822
  input_bag_base: null  #optional
  topic_list: null  #necessary if input_bag_base is not null
