task: convert_non_annotated_t4_to_basic_ai
conversion:
  input_base: ./data/non_annotated_t4_format
  output_base: ./data/basic_ai_format
  annotation_hz: 1
  workers_number: 12
  camera_sensors:
    - channel: CAM_FRONT
    - channel: CAM_FRONT_RIGHT
    - channel: CAM_BACK_RIGHT
    - channel: CAM_BACK
    - channel: CAM_BACK_LEFT
    - channel: CAM_FRONT_LEFT
