task: convert_fastlabel_2d_to_t4
description:
  visibility:
    full: "No occlusion of the object."
    most: "Object is occluded, but by less than 50%."
    partial: "The object is occluded by more than 50% (but not completely)."
    none: "The object is 90-100% occluded and no points/pixels are visible in the label."
  camera_index:
    CAM_FRONT: 0
    CAM_FRONT_RIGHT: 1
    CAM_BACK_RIGHT: 2
    CAM_BACK: 3
    CAM_BACK_LEFT: 4
    CAM_FRONT_LEFT: 5

conversion:
  input_base: ./data/non_annotated_t4_format
  input_anno_base: ./data/fastlabel
  input_bag_base: ./data/rosbag2
  output_base: ./data/t4_format
  topic_list: ./config/topic_list_sample.yaml
  dataset_corresponding:
    # input t4dataset_name: FastLabel json file name
    2-4: 2-4.json
    2-6: 2-6.json
    4-6-2: 4-6-2.json
    6-1: 6-1.json
