task: convert_deepen_to_t4
description:
  visibility:
    full: "No occlusion of the object."
    most: "Object is occluded, but by less than 50%."
    partial: "The object is occluded by more than 50% (but not completely)."
    none: "The object is 90-100% occluded and no points/pixels are visible in the label."
  camera_index:
    CAM_BACK_RIGHT: 0
    CAM_BACK: 1
    CAM_BACK_LEFT: 2
    CAM_FRONT: 3
    CAM_FRONT_LEFT: 4
    CAM_FRONT_NARROW: 5
    CAM_FRONT_RIGHT: 6
    CAM_FRONT_WIDE: 7
  with_lidar: true
  with_lidarseg: true

conversion:
  label_info: # for 3D/2D box only annotations, it is OK to skip specifying this field
    label_type: 3d_point
    label_format: paint_3d
  input_base: /home/kokseangtantier4jp/lidar_semseg_sample/data/non_annotated_t4_format
  input_anno_file: /home/kokseangtantier4jp/lidar_semseg_sample/data/deepen_format/lidarseg_annotations_accepted_deepen.json
  input_bag_base: /home/kokseangtantier4jp/lidar_semseg_sample/data/rosbag2
  output_base: /home/kokseangtantier4jp/lidar_semseg_sample/data/t4_format
  topic_list: ./config/topic_list_sample.yaml
  ignore_interpolate_label: true
  dataset_corresponding:
    sample_lidarseg: 8CasOTR8FZY250hs6UNAttBi
