mandatory_topic_list:
 - /sensing/lidar/concatenated/pointcloud
 - /tf
 - /tf_static
 - /sensing/camera/camera0/image_rect_color/compressed
 - /sensing/camera/camera1/image_rect_color/compressed
 - /sensing/camera/camera2/image_rect_color/compressed
 - /sensing/camera/camera3/image_rect_color/compressed
 - /sensing/camera/camera4/image_rect_color/compressed
 - /sensing/camera/camera5/image_rect_color/compressed
 - /localization/kinematic_state
topic_list:
 - /sensing/lidar/left/velodyne_packets
 - /sensing/lidar/rear/velodyne_packets
 - /sensing/lidar/right/velodyne_packets
 - /sensing/lidar/top/velodyne_packets
 - /sensing/lidar/concatenated/pointcloud
 - /sensing/camera/camera0/image_rect_color/compressed
 - /sensing/camera/camera1/image_rect_color/compressed
 - /sensing/camera/camera2/image_rect_color/compressed
 - /sensing/camera/camera3/image_rect_color/compressed
 - /sensing/camera/camera4/image_rect_color/compressed
 - /sensing/camera/camera5/image_rect_color/compressed
 - /sensing/camera/camera0/camera_info
 - /sensing/camera/camera1/camera_info
 - /sensing/camera/camera2/camera_info
 - /sensing/camera/camera3/camera_info
 - /sensing/camera/camera4/camera_info
 - /sensing/camera/camera5/camera_info
 - /sensing/radar/front_center/from_can_bus
 - /sensing/radar/front_left/from_can_bus
 - /sensing/radar/front_right/from_can_bus
 - /sensing/radar/rear_center/from_can_bus
 - /sensing/radar/rear_left/from_can_bus
 - /sensing/radar/rear_right/from_can_bus
 - /pacmod/from_can_bus
 - /can_rx
 - /pacmod/can_rx
 - /sensing/gnss/ublox/fix_velocity
 - /sensing/gnss/ublox/nav_sat_fix
 - /sensing/gnss/ublox/navpvt
 - /sensing/gnss/septentrio/nav_sat_fix
 - /sensing/gnss/fixed
 - /sensing/gnss/pose
 - /sensing/gnss/pose_with_covariance
 - /sensing/imu/tamagawa/imu_raw
 - /tf
 - /tf_static
 - /localization/kinematic_state
