task: upload_dataset
conversion:
  input_base: ./data/kognic_format
  organization_id: 114
  workspace_id: efa90d1e-99bc-4064-98bb-5bfc8758157d
  project_external_id: test_upload_data
  # batch: <batch_external_id>  # optional, defaults to the latest open batch
  target_hz: 10
  dryrun: false
  motion_compensate: false
  include_imu_data: true
  write_debug_frames: false
