task: upload_dataset
conversion:
  input_base: ./data/deepen_format
  labeling_profile_id: NtUh5kHCy7Pl9L4HpO5iDrW0
  labeling_mode: label_by_label  #label_by_label or frame_by_frame
  dataset_type: 3d  #3d or video or images
  tags: []
