# Category list of surfaces. Each category does not have "instance ID".
# Reference: https://drive.google.com/file/d/132nKnXc7vq9Bjj0quoXDFGi9q5jtrXuY/view?usp=drive_link
- road
- sidewalk
- wall
- fence
- poll
- vegetation
- terrain
- sky
